language: ruby
rvm:
  - 2.0.0
before_script:
  - 'cp config/app_config.example.yml config/app_config.yml'
  - "psql -c 'create database mawidaqa_test;' -U postgres"
  - 'bundle exec rake db:migrate --trace'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
