smtp:
  address: 'smtp.gmail.com'
  port: 587
  domain: 'gmail.com'
  user_name: 'username@change.me'
  password: '<password>'
  authentication: 'plain'
  enable_starttls_auto: true

public_host: 'lvh.me'
support_email: 'noreply@change.me'
