common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'mawidaqa' %>
  password: <%= ENV['TRAVIS'] ? '' : 'mawidaqa' %>

development:
  database: mawidaqa_development
  <<: *common

test:
  database: mawidaqa_test
  <<: *common

production:
  database: mawidaqa_production
  <<: *common

sandbox:
  database: mawidaqa_production
  <<: *common
